/**
 * Event Schemas
 *
 * All domain-specific event schemas for LogVault audit logging.
 *
 * @module @logvault/schemas/events
 */

// Auth events
export {
  AuthEventSchema,
  AuthLoginSchema,
  AuthLogoutSchema,
  AuthLoginFailedSchema,
  AuthPasswordChangedSchema,
  AuthPasswordResetRequestedSchema,
  AuthMfaEnabledSchema,
  AuthMfaDisabledSchema,
  AuthSessionCreatedSchema,
  AuthSessionRevokedSchema,
  AuthMethodSchema,
  MfaMethodSchema,
  AUTH_ACTIONS,
  type AuthEvent,
  type AuthLoginEvent,
  type AuthLogoutEvent,
  type AuthLoginFailedEvent,
  type AuthPasswordChangedEvent,
  type AuthPasswordResetRequestedEvent,
  type AuthMfaEnabledEvent,
  type AuthMfaDisabledEvent,
  type AuthSessionCreatedEvent,
  type AuthSessionRevokedEvent,
  type AuthMethod,
  type MfaMethod,
  type AuthAction,
} from "./auth";

// User events
export {
  UserEventSchema,
  UserCreatedSchema,
  UserUpdatedSchema,
  UserDeletedSchema,
  UserSuspendedSchema,
  UserReactivatedSchema,
  UserRoleChangedSchema,
  UserEmailVerifiedSchema,
  UserInvitedSchema,
  UserSourceSchema,
  DataRetentionSchema,
  USER_ACTIONS,
  type UserEvent,
  type UserCreatedEvent,
  type UserUpdatedEvent,
  type UserDeletedEvent,
  type UserSuspendedEvent,
  type UserReactivatedEvent,
  type UserRoleChangedEvent,
  type UserEmailVerifiedEvent,
  type UserInvitedEvent,
  type UserSource,
  type DataRetention,
  type UserAction,
} from "./user";

// Access events
export {
  AccessEventSchema,
  AccessGrantedSchema,
  AccessRevokedSchema,
  AccessDeniedSchema,
  AccessRequestedSchema,
  AccessApprovedSchema,
  AccessRejectedSchema,
  AccessExpiredSchema,
  ACCESS_ACTIONS,
  type AccessEvent,
  type AccessGrantedEvent,
  type AccessRevokedEvent,
  type AccessDeniedEvent,
  type AccessRequestedEvent,
  type AccessApprovedEvent,
  type AccessRejectedEvent,
  type AccessExpiredEvent,
  type AccessAction,
} from "./access";

// Document events
export {
  DocumentEventSchema,
  DocumentCreatedSchema,
  DocumentReadSchema,
  DocumentUpdatedSchema,
  DocumentDeletedSchema,
  DocumentSharedSchema,
  DocumentUnsharedSchema,
  DocumentMovedSchema,
  DocumentCopiedSchema,
  DocumentRestoredSchema,
  DocumentExportedSchema,
  DOCUMENT_ACTIONS,
  type DocumentEvent,
  type DocumentCreatedEvent,
  type DocumentReadEvent,
  type DocumentUpdatedEvent,
  type DocumentDeletedEvent,
  type DocumentSharedEvent,
  type DocumentUnsharedEvent,
  type DocumentMovedEvent,
  type DocumentCopiedEvent,
  type DocumentRestoredEvent,
  type DocumentExportedEvent,
  type DocumentAction,
} from "./document";

// Data events
export {
  DataEventSchema,
  DataExportedSchema,
  DataImportedSchema,
  DataDeletedSchema,
  DataAnonymizedSchema,
  DataAccessedSchema,
  DataBackupCreatedSchema,
  DataRestoredSchema,
  DATA_ACTIONS,
  type DataEvent,
  type DataExportedEvent,
  type DataImportedEvent,
  type DataDeletedEvent,
  type DataAnonymizedEvent,
  type DataAccessedEvent,
  type DataBackupCreatedEvent,
  type DataRestoredEvent,
  type DataAction,
} from "./data";

// Billing events
export {
  BillingEventSchema,
  BillingSubscriptionCreatedSchema,
  BillingSubscriptionUpdatedSchema,
  BillingSubscriptionCancelledSchema,
  BillingPaymentSucceededSchema,
  BillingPaymentFailedSchema,
  BillingInvoiceCreatedSchema,
  BillingRefundIssuedSchema,
  BillingPlanChangedSchema,
  BILLING_ACTIONS,
  type BillingEvent,
  type BillingSubscriptionCreatedEvent,
  type BillingSubscriptionUpdatedEvent,
  type BillingSubscriptionCancelledEvent,
  type BillingPaymentSucceededEvent,
  type BillingPaymentFailedEvent,
  type BillingInvoiceCreatedEvent,
  type BillingRefundIssuedEvent,
  type BillingPlanChangedEvent,
  type BillingAction,
} from "./billing";

// System events
export {
  SystemEventSchema,
  SystemApiKeyCreatedSchema,
  SystemApiKeyRevokedSchema,
  SystemConfigChangedSchema,
  SystemWebhookCreatedSchema,
  SystemWebhookDeletedSchema,
  SystemIntegrationEnabledSchema,
  SystemIntegrationDisabledSchema,
  SystemErrorOccurredSchema,
  SystemMaintenanceStartedSchema,
  SystemMaintenanceEndedSchema,
  SYSTEM_ACTIONS,
  type SystemEvent,
  type SystemApiKeyCreatedEvent,
  type SystemApiKeyRevokedEvent,
  type SystemConfigChangedEvent,
  type SystemWebhookCreatedEvent,
  type SystemWebhookDeletedEvent,
  type SystemIntegrationEnabledEvent,
  type SystemIntegrationDisabledEvent,
  type SystemErrorOccurredEvent,
  type SystemMaintenanceStartedEvent,
  type SystemMaintenanceEndedEvent,
  type SystemAction,
} from "./system";
